install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_0.82.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rs -rf public
script:
- hugo
branches:
 only:
 - master